"""empty message

Revision ID: 28dada8dc2a9
Revises: cb0f8afef325
Create Date: 2022-12-27 05:58:24.660373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28dada8dc2a9'
down_revision = 'cb0f8afef325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'split_caption', ['split_caption_id'])
    op.alter_column('utube_content_master', 'play_from',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    op.alter_column('utube_content_master', 'play_to',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utube_content_master', 'play_to',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('utube_content_master', 'play_from',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.drop_constraint(None, 'split_caption', type_='unique')
    # ### end Alembic commands ###
