"""empty message

Revision ID: 75bdc4ab9e8e
Revises: 28dada8dc2a9
Create Date: 2022-12-29 01:49:28.881840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75bdc4ab9e8e'
down_revision = '28dada8dc2a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utube_content_master', 'play_from',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    op.alter_column('utube_content_master', 'play_to',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utube_content_master', 'play_to',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('utube_content_master', 'play_from',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    # ### end Alembic commands ###
