"""empty message

Revision ID: a25c4bbe4705
Revises: 445a347f252d
Create Date: 2022-12-06 04:39:41.444756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a25c4bbe4705'
down_revision = '445a347f252d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utube_content_master', 'play_from',
               existing_type=sa.REAL(),
               comment='',
               existing_nullable=False)
    op.alter_column('utube_content_master', 'play_to',
               existing_type=sa.REAL(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utube_content_master', 'play_to',
               existing_type=sa.REAL(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('utube_content_master', 'play_from',
               existing_type=sa.REAL(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    # ### end Alembic commands ###
