"""empty message

Revision ID: cb0f8afef325
Revises: 1eba3318d2a9
Create Date: 2022-12-23 06:04:05.793479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0f8afef325'
down_revision = '1eba3318d2a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utube_content_master', 'play_from',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    op.alter_column('utube_content_master', 'play_to',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utube_content_master', 'play_to',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('utube_content_master', 'play_from',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    # ### end Alembic commands ###
